version: '3.8'

services:
  event-form-suite:
    build: .
    container_name: event-form-suite
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    volumes:
      # Mount forms directory to persist form instances and databases
      - ./forms:/app/forms
      # Mount a data directory for any additional persistent data
      - ./data:/app/data
      # Optional: Mount public assets if you want to customize them
      - ./public/assets:/app/public/assets
    restart: unless-stopped
    networks:
      - event-form-network

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   container_name: event-form-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/ssl:ro
  #   depends_on:
  #     - event-form-suite
  #   restart: unless-stopped
  #   networks:
  #     - event-form-network

networks:
  event-form-network:
    driver: bridge

volumes:
  # Named volumes for better data persistence management
  forms_data:
  app_data: 